cloud:
  aws:
    stack:
      auto: false
    region:
      auto: false
      static: eu-central-1
    credentials:
      use-default-aws-credentials-chain: true

server:
  forward-headers-strategy: framework

custom:
  invitation-codes: DUKE, HELLO_WORLD, STRATOSPHERIC
  sharing-queue: stratospheric-todo-sharing
  auto-confirm-collaborations: false
